export const SET_DFO_CORE = 'SET_DFO_CORE';
export const REMOVE_DFO_CORE = 'REMOVE_DFO_CORE';
export const ADD_PENDING_TRANSACTION = 'ADD_PENDING_TRANSACTION';
export const REMOVE_PENDING_TRANSACTION = 'REMOVE_PENDING_TRANSACTION';
export const CLEAR_PENDING_TRANSACTIONS = 'CLEAR_PENDING_TRANSACTIONS';