export const SET_FARMING_CONTRACT_STEP = "SET_FARMING_CONTRACT_STEP";
export const UPDATE_FARMING_CONTRACT = "UPDATE_FARMING_CONTRACT";
export const ADD_FARMING_SETUP = "ADD_FARMING_SETUP";
export const REMOVE_FARMING_SETUP = "REMOVE_FARMING_SETUP";